import { Vivienda } from './../clases/vivienda';

export class ModelViviendas{

viviendas: Vivienda[] = [
  {
    direccion: "calle madalena",
    poblacion: "lliria",
    precio: 300,
    alquiler: true,
    foto: "http://formenterain.com/wp-content/uploads/2017/04/Casa-Casbah-5-300x300.jpg",
    descripcion: "casa muy soleada",
    numhab: 3,
    telefono: "962745874",
    correo: "benitocamelas@gmail.com",
  },
  {
    direccion: "calle mostoles",
    poblacion: "massanasa",
    precio: 120000,
    alquiler: false,
    foto: "http://huetearquitectos.com/wp-content/uploads/2017/06/casa-marbella-300x300.jpg",
    descripcion: "casa muy fresquita",
    numhab: 2,
    telefono: "962755574",
    correo: "evafinasegura@gmail.com",
  },
  {
    direccion: "calle rioja",
    poblacion: "catarroja",
    precio: 450,
    alquiler: true,
    foto: "http://www.cubeinteriora.es/wp-content/uploads/2017/02/construccion-casa-madera4-300x300.jpg",
    descripcion: "casa muy silenciosa",
    numhab: 3,
    telefono: "968885874",
    correo: "jhonsnow@gmail.com",
  },
  {
    direccion: "calle meliana",
    poblacion: "benetusser",
    precio: 320,
    alquiler: true,
    foto: "http://loff.it/wp-content/uploads/2017/04/loffit-fiera-vista-en-siesta-key-una-casa-de-escandalo-a-subasta-en-florida-02-300x300-1493322247.jpg",
    descripcion: "casa muy calentita",
    numhab: 4,
    telefono: "962745222",
    correo: "espartaco@gmail.com",
  },
  {
    direccion: "calle benidorm",
    poblacion: "sedavi",
    precio: 200000,
    alquiler: false,
    foto: "http://inmobiliariagoals.com/wp-content/uploads/2017/04/Casa_La_Campi%C3%B1a_Xochitepec_Morelos_04-300x300.jpg",
    descripcion: "casa con muchas ventanas",
    numhab: 2,
    telefono: "962748774",
    correo: "majareta@gmail.com",
  },
  {
    direccion: "calle ponferrada",
    poblacion: "catarroja",
    precio: 300,
    alquiler: true,
    foto: "http://loff.it/wp-content/uploads/2017/05/loffit-una-casa-con-vistas-a-oakland-11-300x300.jpeg",
    descripcion: "casa verdaderamente horripilante",
    numhab: 5,
    telefono: "961115874",
    correo: "frodobolson@gmail.com",
  },
  {
    direccion: "calle ferrol",
    poblacion: "meliana",
    precio: 500000,
    alquiler: false,
    foto: "http://kalibienesraices.com/wp-content/uploads/2017/03/Render-Fachada-300x300.png",
    descripcion: "casa muy centrica",
    numhab: 3,
    telefono: "962733374",
    correo: "marea@gmail.com",
  },
  {
    direccion: "calle flexo",
    poblacion: "massanasa",
    precio: 320,
    alquiler: true,
    foto: "http://formenterain.com/wp-content/uploads/2017/04/Casa-Casbah-14-300x300.jpg",
    descripcion: "casa grande",
    numhab: 3,
    telefono: "962745874",
    correo: "benitocamelas@gmail.com",
  },
  {
    direccion: "calle chicago",
    poblacion: "massanasa",
    precio: 125000,
    alquiler: false,
    foto: "http://tocarmadera.com/wp-content/uploads/2014/05/MARIA-51-ORIGINAL1-300x300.jpg",
    descripcion: "casa muy pequeña",
    numhab: 1,
    telefono: "962755574",
    correo: "evafinasegura@gmail.com",
  },
  {
    direccion: "calle mirador",
    poblacion: "benisano",
    precio: 430,
    alquiler: true,
    foto: "http://loff.it/wp-content/uploads/2016/12/loffit-la-casa-mas-bella-de-sao-paulo-13-300x300-1482486996.jpg",
    descripcion: "casa muy intima",
    numhab: 4,
    telefono: "968885874",
    correo: "jhonsnow@gmail.com",
  },
  {
    direccion: "calle mallorca",
    poblacion: "benejucar",
    precio: 420,
    alquiler: true,
    foto: "http://loff.it/wp-content/uploads/2016/05/loffit-mosha-house-la-bella-casa-desestructurada-06-300x300.jpg",
    descripcion: "casa muy alejada",
    numhab: 4,
    telefono: "962745222",
    correo: "espartaco@gmail.com",
  },
  {
    direccion: "calle guay",
    poblacion: "benidorm",
    precio: 210000,
    alquiler: false,
    foto: "http://www.alojamientospirineos.com/wp-content/uploads/2016/01/casa-trallero06-300x300.jpg",
    descripcion: "casa con chimenea",
    numhab: 2,
    telefono: "962748774",
    correo: "majareta@gmail.com",
  },
  {
    direccion: "calle truño",
    poblacion: "valencia",
    precio: 200,
    alquiler: true,
    foto: "http://loff.it/wp-content/uploads/2015/12/loffit-se-vende-la-casa-de-naomi-watts-en-los-hamptons-04-300x300.jpg",
    descripcion: "casa con buen olor",
    numhab: 5,
    telefono: "961115874",
    correo: "frodobolson@gmail.com",
  },
  {
    direccion: "calle rioja",
    poblacion: "xirivella",
    precio: 550000,
    alquiler: false,
    foto: "http://www.galicianrustic.com/wp-content/uploads/Bonita-casa-main-300x300.jpg",
    descripcion: "casa luminosa",
    numhab: 3,
    telefono: "962733374",
    correo: "marea@gmail.com",
  },

  {
    direccion: "calle madalena",
    poblacion: "lliria",
    precio: 300,
    alquiler: true,
    foto: "http://formenterain.com/wp-content/uploads/2017/04/Casa-Casbah-5-300x300.jpg",
    descripcion: "casa muy soleada",
    numhab: 3,
    telefono: "962745874",
    correo: "benitocamelas@gmail.com",
  },
  {
    direccion: "calle mostoles",
    poblacion: "massanasa",
    precio: 120000,
    alquiler: false,
    foto: "http://huetearquitectos.com/wp-content/uploads/2017/06/casa-marbella-300x300.jpg",
    descripcion: "casa muy fresquita",
    numhab: 2,
    telefono: "962755574",
    correo: "evafinasegura@gmail.com",
  },
  {
    direccion: "calle rioja",
    poblacion: "catarroja",
    precio: 450,
    alquiler: true,
    foto: "http://www.cubeinteriora.es/wp-content/uploads/2017/02/construccion-casa-madera4-300x300.jpg",
    descripcion: "casa muy silenciosa",
    numhab: 3,
    telefono: "968885874",
    correo: "jhonsnow@gmail.com",
  },
  {
    direccion: "calle meliana",
    poblacion: "benetusser",
    precio: 320,
    alquiler: true,
    foto: "http://loff.it/wp-content/uploads/2017/04/loffit-fiera-vista-en-siesta-key-una-casa-de-escandalo-a-subasta-en-florida-02-300x300-1493322247.jpg",
    descripcion: "casa muy calentita",
    numhab: 4,
    telefono: "962745222",
    correo: "espartaco@gmail.com",
  },
  {
    direccion: "calle benidorm",
    poblacion: "sedavi",
    precio: 200000,
    alquiler: false,
    foto: "http://inmobiliariagoals.com/wp-content/uploads/2017/04/Casa_La_Campi%C3%B1a_Xochitepec_Morelos_04-300x300.jpg",
    descripcion: "casa con muchas ventanas",
    numhab: 2,
    telefono: "962748774",
    correo: "majareta@gmail.com",
  },
  {
    direccion: "calle ponferrada",
    poblacion: "catarroja",
    precio: 300,
    alquiler: true,
    foto: "http://loff.it/wp-content/uploads/2017/05/loffit-una-casa-con-vistas-a-oakland-11-300x300.jpeg",
    descripcion: "casa verdaderamente horripilante",
    numhab: 5,
    telefono: "961115874",
    correo: "frodobolson@gmail.com",
  },
  {
    direccion: "calle ferrol",
    poblacion: "meliana",
    precio: 500000,
    alquiler: false,
    foto: "http://kalibienesraices.com/wp-content/uploads/2017/03/Render-Fachada-300x300.png",
    descripcion: "casa muy centrica",
    numhab: 3,
    telefono: "962733374",
    correo: "marea@gmail.com",
  },
  {
    direccion: "calle flexo",
    poblacion: "massanasa",
    precio: 320,
    alquiler: true,
    foto: "http://formenterain.com/wp-content/uploads/2017/04/Casa-Casbah-14-300x300.jpg",
    descripcion: "casa grande",
    numhab: 3,
    telefono: "962745874",
    correo: "benitocamelas@gmail.com",
  },
  {
    direccion: "calle chicago",
    poblacion: "massanasa",
    precio: 125000,
    alquiler: false,
    foto: "http://tocarmadera.com/wp-content/uploads/2014/05/MARIA-51-ORIGINAL1-300x300.jpg",
    descripcion: "casa muy pequeña",
    numhab: 1,
    telefono: "962755574",
    correo: "evafinasegura@gmail.com",
  },
  {
    direccion: "calle mirador",
    poblacion: "benisano",
    precio: 430,
    alquiler: true,
    foto: "http://loff.it/wp-content/uploads/2016/12/loffit-la-casa-mas-bella-de-sao-paulo-13-300x300-1482486996.jpg",
    descripcion: "casa muy intima",
    numhab: 4,
    telefono: "968885874",
    correo: "jhonsnow@gmail.com",
  },
  {
    direccion: "calle mallorca",
    poblacion: "benejucar",
    precio: 420,
    alquiler: true,
    foto: "http://loff.it/wp-content/uploads/2016/05/loffit-mosha-house-la-bella-casa-desestructurada-06-300x300.jpg",
    descripcion: "casa muy alejada",
    numhab: 4,
    telefono: "962745222",
    correo: "espartaco@gmail.com",
  },
  {
    direccion: "calle guay",
    poblacion: "benidorm",
    precio: 210000,
    alquiler: false,
    foto: "http://www.alojamientospirineos.com/wp-content/uploads/2016/01/casa-trallero06-300x300.jpg",
    descripcion: "casa con chimenea",
    numhab: 2,
    telefono: "962748774",
    correo: "majareta@gmail.com",
  },
  {
    direccion: "calle truño",
    poblacion: "valencia",
    precio: 200,
    alquiler: true,
    foto: "http://loff.it/wp-content/uploads/2015/12/loffit-se-vende-la-casa-de-naomi-watts-en-los-hamptons-04-300x300.jpg",
    descripcion: "casa con buen olor",
    numhab: 5,
    telefono: "961115874",
    correo: "frodobolson@gmail.com",
  },
  {
    direccion: "calle rioja",
    poblacion: "xirivella",
    precio: 550000,
    alquiler: false,
    foto: "http://www.galicianrustic.com/wp-content/uploads/Bonita-casa-main-300x300.jpg",
    descripcion: "casa luminosa",
    numhab: 3,
    telefono: "962733374",
    correo: "marea@gmail.com",
  },

];

}
